# Default exec command when opening file.
# If not set, will default to $EDITOR.
# default: nvim

# Whether to match the behavior of Vim's exit keybindings.
match_vim_exit_behavior: false

# key (the command you want to use when opening file): [values] (extensions)
# In the key, You can use arguments.
exec:
  zathura:
    [pdf, epub]
 swayimg:
  [jpg, jpeg, png, gif, svg, hdr]

# Whether to do the case-insensitive search by `/`.
ignore_case: true
