#!/bin/sh

if [ "$#" -eq 0 ]; then
  echo "Path not specified."
  exit 1
elif [ ! -d "$1" ]; then
  echo "The specified path does not exist."
  exit 1
fi

bk() {
  gnu-rsync --verbose --archive -hh --delete --partial "$@";
}

while true; do
  read -p "Proceeding with "$1" ? " yn
  case $yn in
    [Yy]* )
      start=$(date "+%s")
      mkdir -p "$1"/backup
      bk "$HOME/music"            "$1"/backup
      bk "$HOME/sources/personal" "$1"/backup/sources
      bk "$HOME/computers"        "$1"/backup
      bk "$HOME/vault"            "$1"/backup
      end=$(date "+%s")
      notify-send "Backup done. Took $((end-start)) seconds"
      break
      ;;
    [Nn]* )
      exit
      ;;
    * )
      echo "Please answer yes or no."
      ;;
  esac
done
