#!/bin/sh

# see https://wiki.archlinux.org/title/Rsync

new_args=()
for i in "${@}"; do
    case "${i}" in
        /)
            i="/"
        ;;
        */)
            i="${i%/}"
        ;;
        esac
    new_args+=("${i}")
done

exec rsync "${new_args[@]}"
